version: 2

updates:
  - package-ecosystem: "nuget"
    directories: 
      - "/src/*"
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns: [ "*" ]
  - package-ecosystem: "nuget"
    directories: 
      - "/tests/*"
    schedule:
      interval: "weekly"
    groups:
      tests:
        patterns: [ "*" ]
